# Generated by Django 4.2.9 on 2024-03-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_shoe_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="total_price",),
    ]
