# Generated by Django 4.2.7 on 2024-03-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='sub_category',
            field=models.CharField(choices=[('SPORTS', 'Sports'), ('FORMALS', 'Formals'), ('SANDALS', 'Sandals'), ('SNEAKERS', 'Sneakers')], default=None, max_length=20),
        ),
    ]
