# Generated by Django 4.2.7 on 2024-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_shoe_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('SPORTS', 'Sports'), ('FORMALS', 'Formals'), ('SANDALS', 'Sandals'), ('SNEAKERS', 'Sneakers')], max_length=20, null=True),
        ),
    ]
