# Generated by Django 4.2.7 on 2024-03-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_shoe_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='sub_category',
        ),
    ]
